---
- name: Install required packages using Python 2.*
  when: python2_path is defined
  package: name={{ item }} state=present
  with_items:
    - "gcc"
    - "gcc-c++"
    - "make"
    - "automake"
    - "autoconf"
    - "libtool"
  vars:
    ansible_python_interpreter: "{{ python2_path }}"
  failed_when: false

- name: Install required packages using Python 3.*
  package: name={{ item }} state=present
  with_items:
    - "gcc"
    - "gcc-c++"
    - "make"
    - "automake"
    - "autoconf"
    - "libtool"
  failed_when: false



