---

- name: "Ensure dingo user group exist: {{ dingo_group }}"
  group: name={{ dingo_group }} state=present

- name: "Ensure dingo user exist {{ dingo_user }}"
  user: name={{ dingo_user }} group={{ dingo_group }}

- name: "Remove dingo home/log/data directories if exist"
  file: path="{{ item }}" state=absent
  with_items: 
    - "{{ dingo_log_path }}"
    - "{{ dingo_data_path }}"


- name: "Create dingo directories"
  file: path="{{item}}" state=directory owner={{dingo_user}} group={{dingo_group}}
  with_items:
    - "{{ dingo_log_path }}"
    - "{{ dingo_data_path }}"
    - "{{ dingo_executor_server_db_path }}"
    - "{{ dingo_executor_raft_log_path }}"
    - "{{ dingo_executor_raft_db_path }}"