---

# for debugger to display variables
- name: debug
  debug: 
    msg:
    - "Coordinator Exchange Connection: {{ dingo_coordinator_exchange_connection_list }}"

- name: "Generate dingo configuration files"
  template: src={{ item.src }} dest={{ item.dest }} owner={{ dingo_user }} group={{ dingo_group }} mode=0755
  with_items:
    - {
      src: "logback-executor.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-executor.xml"
    }
    - {
      src: "logback-proxy.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-proxy.xml"
    }
    - {
      src: "logback-web.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-web.xml"
    }
    - {
      src: "logback.xml.j2",
      dest: "{{ dingo_home }}/conf/logback.xml"
    }
    - {
      src: "client.yaml.j2",
      dest: "{{ dingo_home }}/conf/client.yaml"
    }
    - {
      src: "start-executor.sh.j2",
      dest: "{{ dingo_home }}/bin/start-executor.sh"
    }
    - {
      src: "replace-executor.sh.j2",
      dest: "{{ dingo_home }}/bin/replace-executor.sh"
    }
    - {
      src: "start-web.sh.j2",
      dest: "{{ dingo_home }}/bin/start-web.sh"
    }
    - {
      src: "start-proxy.sh.j2",
      dest: "{{ dingo_home }}/bin/start-proxy.sh"
    }
    - {
      src: "stop-all-component.sh.j2",
      dest: "{{ dingo_home }}/bin/stop-all-component.sh"
    }
    - {
      src: "executor.yaml.j2",
      dest: "{{ dingo_home }}/conf/executor.yaml"
    }
    - {
      src: "application-proxy-dev.yaml.j2",
      dest: "{{ dingo_home }}/conf/application-proxy-dev.yaml"
    }
    - {
      src: "application-proxy.yaml.j2",
      dest: "{{ dingo_home }}/conf/application-proxy.yaml"
    }
    - {
      src: "application-web.yaml.j2",
      dest: "{{ dingo_home }}/conf/application-web.yaml"
    }
    - {
      src: "application-web-dev.yaml.j2",
      dest: "{{ dingo_home }}/conf/application-web-dev.yaml"
    }

- name: "Remove unused configure files"
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ dingo_home }}/conf/config.yaml"
