---

# stop all the coordinator and executor
- name: "Stop Coordinator and Executor on all host"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/stop-all-component.sh"
  args:
    chdir: "{{ dingo_home }}"

- set_fact: remote_prometheus_javaagent_path={{ dingo_home }}/libs/

# copy jmx_prometheus_javaagent-0.17.2.jar to remote host
- name: "Copy jmx_prometheus_javaagent-0.17.2.jar to remote host"
  copy: src={{ jmx_prometheus_javaagent_local_file }} dest={{ remote_prometheus_javaagent_path }}
  when: install_monitor_web

# create jmx_config.yaml
- name: "Create jmx_config.yaml"
  become: true
  template:
    src: "jmx_config.yaml.j2"
    dest: "{{ dingo_home }}/conf/jmx_config.yaml"
  when: is_dingo_executor


# start executor
- name: "Start Executor using Shell Script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/start-executor.sh "
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_executor

# Start dingo proxy
- name: "Start Dingo Proxy appliaction using Shell script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/start-proxy.sh"
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_proxy

# Start dingo web
- name: "Start Dingo Web appliaction using Shell script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/start-web.sh"
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_web

