---

# stop all the coordinator and executor
- name: "Stop Coordinator and Executor on all host"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/stop-all-component.sh"
  args:
    chdir: "{{ dingo_home }}"

# start executor
- name: "Start Executor using Shell Script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/start-executor.sh " 
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_executor

# Start dingo proxy 
- name: "Start Dingo Proxy appliaction using Shell script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./bin/start-proxy.sh"
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_proxy

