---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the openldap and required Packages for RedHat
  ansible.builtin.yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install the openldap and required Packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install the openldap and required Packages for Rocky
  ansible.builtin.yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'Rocky'

- name: Delete the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  register: root_password

- name: Copy the slapd.conf configuration file for Redhat
  template: src=slapd.conf.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf_ubuntu.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify: 
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf

- name: Copy the domain.ldif configuration file for Redhat
  template: src=domain.ldif.j2 dest={{ openldap_server_app_path }}/domain.ldif
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the base-groups.ldif configuration file for Redhat
  template: src=base-groups.ldif.j2 dest={{ openldap_server_app_path }}/base-groups.ldif
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the group.ldif configuration file for Redhat
  template: src=group.ldif.j2 dest={{ openldap_server_app_path }}/group.ldif
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the dingo.ldif configuration file for Redhat
  template: src=dingo.ldif.j2 dest={{ openldap_server_app_path }}/dingo.ldif
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd