---

#The domain prefix for ldap
openldap_server_domain_name: localdomain.com

#This is the password for admin for openldap 
openldap_server_rootpw: passme

#The self signed ssl parameters
openldap_server_country: US
openldap_server_state: oregon
openldap_server_location: portland
openldap_server_organization: IT

openldap_server_enable_ssl: false

openldap_server_app_path: "/etc/openldap/"
