---

#- name: install Vim
#  dnf:
#    name: vim
#    state: present

#- name: install Tmux 
#  dnf:
#    name: tmux
#    state: present

- name: "Install required packages"
  package: name={{ item }} state=present
  with_items:
    - "tar"
    - "vim"
    - "tmux"
    - "unzip"
    - "libaio-devel"
    - "boost-devel"
  become: yes