
- name: Ensure directory for core file pattern exists
  file:
    path: "{{ core_file_dir }}"
    state: directory
    mode: "0777"

- name: Enable core dumps in /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - "* soft core unlimited"
    - "* hard core unlimited"

- name: Set suid_dumpable value to 2
  sysctl:
    name: fs.suid_dumpable
    value: 2
    state: present
    reload: yes

- name: Set core file pattern in /etc/sysctl.conf
  sysctl:
    name: kernel.core_pattern
    value: "{{ core_file_dir }}/core.%e.%p.%t"
    state: present
    reload: yes