- name: Ensure directory for core file pattern exists
  file:
    path: "{{ installer_root_path }}/corefiles"
    state: directory
    mode: "0777"

- name: Enable core dumps in /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - "* soft core unlimited"
    - "* hard core unlimited"

- name: Set core file pattern in /etc/sysctl.conf
  sysctl:
    name: kernel.core_pattern
    value: "{{ installer_root_path }}/corefiles/core.%e.%p.%t"
    state: present
    reload: yes