
- name: Ensure directory for core file pattern exists
  file:
    path: "{{ core_file_dir }}"
    state: directory
    mode: "0777"

- name: Check if limits.d exists
  stat:
    path: /etc/security/limits.d
  register: directory_stat

- name: Create limits.d directory if it does not exist
  become: yes
  file:
    path: /etc/security/limits.d
    state: directory
    mode: 0755
  when:
    - not directory_stat.stat.exists

- name: Enable core dumps in /etc/security/limits.conf
  copy:
    content: |
      {{ dingo_user }} - core unlimited
      {{ dingo_user }} - nproc {{ ulimit_nproc_limit }}
      {{ dingo_user }} - nofile {{ ulimit_nofile_limit }}
    dest: /etc/security/limits.d/90-dingo.conf
  become: yes
  notify:
    - Reload limits



- name: Set core file pattern in /etc/sysctl.conf
  sysctl:
    name: kernel.core_pattern
    value: "{{ core_file_dir }}/core.%e.%p.%t"
    state: present
    reload: yes