---

- name: "Check current operation is needed"
  meta: end_play
  when: install_system == false

- name: "Install Basic Linux Tools"
  action: resolve_artifacts

- import_tasks: 01_check_install_requirement.yml

- include_tasks: 02_install_system_cfg.yml
  when:  install_system_fileLimits

- import_tasks: 03_hostname.yml

- import_tasks: 04_install_ntp_or_chrony.yml

- include_tasks: 05_install_basic_tools.yml
  when:  install_system_basicTools

- include_tasks: 06_enable_core_dumps.yml
  when:  set_core_file