---
- name: set_fact - add all to group_names
  set_fact:
    create_users_group_names: "{{ group_names|default([]) + ['all'] }}"

- name: debug variable create_users_group_names
  debug: var=create_users_group_names
  when: debug_enabled_default | bool

- name: debug variable users
  debug: var=users
  when: debug_enabled_default | bool

- name: Add group | create primary group before adding user to group
  group:
    name: "{{ item.primarygroup }}"
    gid: "{{ item.primarygid | default(omit) }}"
    state: present
  when: item.primarygroup is defined and item.servers | intersect(create_users_group_names)
  loop: '{{ users }}'
  loop_control:
    label: "primarygroup: {{ item.primarygroup if item.primarygroup is defined else '' }}, primarygid: {{ item.primarygid if item.primarygid is defined else 'default' }}" # noqa 204

# Get unique list of groups to create on the server (var is different on each server)
# Still keeps formatting of comma separated list and converts to list (even if whitespace)
- name: set_fact - get groups as list per server
  set_fact:
    groups_as_list: "{{ (groups_as_list|default([]) + item.groups.split(','))|map('trim')|list|sort|unique }}"
  loop: '{{ users }}'
  when: item.groups is defined and item.servers | intersect(create_users_group_names)
  loop_control:
    label: "username: {{ item.username }}, groups_as_list: {{ item.groups if item.groups is defined else '' }}"

- name: debug show groups_as_list
  debug: var=groups_as_list
  when: debug_enabled_default | bool

- name: Add group | create groups before adding user to group
  group:
    name: "{{ item }}"
    state: present
  when: groups_as_list is defined
  loop: "{{ groups_as_list }}"
  loop_control:
    label: "groups: {{ item }}"

- name: Encrypt password and set to variable
  set_fact:
    installer_encrypted_password: "{{ installer_password | password_hash('sha512') }}"

- name: Add users | create users, shell, home dirs
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit, True) }}"
    password: "{{installer_encrypted_password}}"
    update_password: "{{ item.update_password if item.update_password is defined else default_update_password }}"
    group: "{{ item.primarygroup | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell if item.shell is defined else default_shell }}"
    createhome: yes
    system: "{{ item.system | default(omit) }}"
    comment: "{{ item.comment if item.comment is defined else '' }}"
    state: present #hard-coded in case user sets state of absent. Choice made to never delete accounts!
  when: item.user_state == 'present' and item.servers | intersect(create_users_group_names)
#works but not multiple servers #and 'centos6' in "{{ create_users_group_names }}"
  loop: '{{ users }}'
  loop_control:
    label: "username: {{ item.username }}, user_state: {{ item.user_state }}, password: {{ 'True' if item.password is defined else 'False' }}, update_password: {{ item.update_password if item.update_password is defined else default_update_password }}, primarygroup: {{ item.primarygroup if item.primarygroup is defined else ''}}, groups: {{ item.groups if item.groups is defined else ''}}, servers: {{ item.servers if item.servers is defined else '' }}, group_names: {{ create_users_group_names }}" # noqa 204

- name: SSH Keys | Generate ssh key
  user:
    name: "{{ item.username }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(false) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(omit) }}"
    # generate_ssh_key_comment: "{{ item.generate_ssh_key_comment | default(omit) }}"
    # generate_ssh_key_comment: "{{ item.username }}@{{ ansible_hostname }}"
    ssh_key_comment: "{{ item.generate_ssh_key_comment if item.generate_ssh_key_comment is defined else default_generate_ssh_key_comment }}"
  when: item.no_passwd_login|d(false)|bool == true and item.servers | intersect(create_users_group_names)
  loop: '{{ users }}'
  loop_control:
    label: "username: {{ item.username }}, no_passwd_login: {{ item.no_passwd_login }}, generate_ssh_key: {{ 'True' if item.generate_ssh_key is defined else 'False' }}, ssh_key_bits: {{ item.ssh_key_bits if item.ssh_key_bits is defined else '' }}, ssh_key_passphrase: {{ 'True' if item.ssh_key_passphrase is defined else 'False' }}, generate_ssh_key_comment: {{ item.generate_ssh_key_comment if item.generate_ssh_key_comment is defined else default_generate_ssh_key_comment }}"


- name: deliver SSH Keys | Add authorized key for ssh key authentication
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '/home/'+item.username+'/.ssh/id_rsa.pub') }}"
    state: present
  when: item.no_passwd_login|d(false)|bool == true and item.servers | intersect(create_users_group_names)
  loop: '{{ users }}'
  loop_control:
    label: "username: {{ item.username }}, no_passwd_login: {{ item.no_passwd_login }}, exclusive_ssh_key: {{ item.exclusive_ssh_key if item.exclusive_ssh_key is defined else 'False' }}" # noqa 204


- name: Sudo | add to sudoers file and validate
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ item.username }} '
    line: "{{ item.username }} ALL=(ALL) {{ 'NOPASSWD:' if ( item.use_sudo_nopass|d(false) )  else '' }}ALL"
    validate: 'visudo -cf %s'
  environment:
    PATH: /usr/sbin:/usr/local/sbin:/sbin
  when: item.use_sudo|d(false)|bool == true and item.servers | intersect(create_users_group_names) # noqa 601
  loop: '{{ users }}'
  loop_control:
    label: "username: {{ item.username }}, use_sudo: {{ item.use_sudo|d(false) }}, use_sudo_nopass: {{ item.use_sudo_nopass|d(false) }}"

- name: Sudo | remove from sudoers file and validate
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^{{ item.username }} '
    line: '{{ item.username }}'
    validate: 'visudo -cf %s'
  environment:
    PATH: /usr/sbin:/usr/local/sbin:/sbin
  when: item.use_sudo|d(false)|bool == false and item.servers | intersect(create_users_group_names) # noqa 601
  loop: '{{ users }}'
  loop_control:
    label: "username: {{ item.username }}, use_sudo: {{ item.use_sudo|d(false) }}"
