---

# stop all the coordinator and store
- name: "Stop and Del db Coordinator on all host"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./scripts/start-coordinator.sh clean"
  args:
    chdir: "{{ dingo_store_home }}"
  when: is_dingo_store_coordinator

# stop all the coordinator and store
- name: "Stop and Del db Store on all host"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./scripts/start-store.sh clean"
  args:
    chdir: "{{ dingo_store_home }}"
  when: is_dingo_store_store

# start coordinator
- name: "Deploy and Start Coordinator using Script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./scripts/start-coordinator.sh cleanstart" 
  args:
    chdir: "{{ dingo_store_home }}"
  when: is_dingo_store_coordinator

- name: "Sleep wait coordinator start"
  shell: "sleep 20"

# start store
- name: "Deploy and Start Store using Shell Script"
  become: true
  become_user: "{{ dingo_user }}"
  shell: "/bin/bash ./scripts/start-store.sh cleanstart" 
  args:
    chdir: "{{ dingo_store_home }}"
  when: is_dingo_store_store

