---
- name: "Check prometheus should install or Not"
  meta: end_play
  when: install_prometheus == false

- name: "Load artifacts info"
  action: resolve_artifacts

- name: Gather facts from extra hosts (regardless of limit or tags)
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['all'] }}"

- import_tasks: 03_prometheus_server.yml

#- import_tasks: 04_add_target.yml