---

- name: "Remove previous install directories"
  file: path={{ item }} state=absent
  with_items:
  - "{{ jdk_home }}"

- set_fact: remote_tarball_path={{ installer_cache_path }}/{{ cfg_jdk_local_path | basename}}

- name: "Ensure installer cache directory {{ installer_cache_path }}"
  file: path={{ installer_cache_path }} state=directory

- name: "Copy tarball to remote host {{ remote_tarball_path }}"
  copy: src={{ cfg_jdk_local_path }} dest={{ remote_tarball_path }}

- name: "Ensure jdk directories"
  file: path={{ item }} state=directory owner={{ jdk_user }} group={{ jdk_group }}
  with_items:
  - "{{ jdk_home }}"

- name: "Unarchive {{ remote_tarball_path }} to {{ jdk_home }}"
  unarchive:
    src: "{{ remote_tarball_path}}"
    dest: "{{ jdk_home }}"
    owner: "{{ jdk_user }}"
    group: "{{ jdk_group }}"
    remote_src: yes
    extra_opts: ['--strip-components=1']

- name: "Set ownership of {{ jdk_home }} to {{ jdk_user }}"
  file: path={{ jdk_home }} owner={{ jdk_user }} group={{ jdk_group }} recurse=yes

- name: "Delete temporary tarball file: {{ remote_tarball_path}}"
  file: path={{ remote_tarball_path }} state=absent
  when: delete_cache_after_install
