---


#---------------------------------
# 3.1 ADD Dingo_store nodes
#---------------------------------
- hosts:
    - scaling_in_dingo
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=scaling_in_dingo
      when: install_dingo_store