---


#---------------------------------
# 6. Install node_exporter 
#---------------------------------

- hosts:
    - all_nodes
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=node_exporter
      when: install_node_exporter
