---
#---------------------------------
# 2_1. Check Port Conflicts
#---------------------------------
- hosts:
    - localhost
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=check_ports
      when: check_port_conflicts


#---------------------------------
# 6. Install node_exporter 
#---------------------------------

- hosts:
    - all_nodes
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=node_exporter
      when: install_node_exporter
