---

#---------------------------------
# 7. Install process_exporter
#---------------------------------
- hosts:
    - all_nodes
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=process_exporter
      when: install_process_exporter
