---

#---------------------------------
# 9. Install monitor web
#---------------------------------

- hosts:
    - web
  vars_files:
    - ../group_vars/all/_shared.yml
  tasks:
    - include_role: name=nginx
      when: install_monitor_web

