---
name: dingodb-deploy
version: develop
artifacts:
  - {name: "cfg_jdk_local_path",  path_in_repo: "jdk-8u171-linux-x64.tar.gz" }
  - {name: "cfg_system_open_file_limits_path",  path_in_repo: "system/centos8/limits/limits.conf" }
  - {name: "cfg_dingodb_store_local_path", path_in_repo: "dingo.tar.gz"}
  - {name: "prometheus_local_file", path_in_repo: "prometheus-2.14.0.linux-amd64.tar.gz" }
  - {name: "grafana_local_file", path_in_repo: "grafana-8.3.3.linux-amd64.tar.gz"}
  - {name: "node_exporter_local_file", path_in_repo: "node_exporter-0.18.1.linux-amd64.tar.gz"}
  - {name: "process_exporter_local_file", path_in_repo: "process-exporter-0.7.10.linux-amd64.tar.gz"}
  - {name: "jmx_prometheus_javaagent_local_file", path_in_repo: "jmx_prometheus_javaagent-0.17.2.jar"}
  - { name: "nginx_src_file",  path_in_repo: "nginx/nginx-1.17.8.tar.gz" }
  - { name: "monitor_web_local_file",  path_in_repo: "nginx/dingo-monitor.tar.gz" }
  - { name: "pcre_src_file",  path_in_repo: "nginx/pcre-8.41.tar.gz" }
  - { name: "openssl_src_file",  path_in_repo: "nginx/OpenSSL_1_1_0f.tar.gz" }
  - { name: "zlib_src_file",  path_in_repo: "nginx/zlib-1.2.11.tar.gz" }
